jobs:
  - os: linux
    dist: bionic
    name: 'Ubuntu 18.04LTS'

  - os: linux
    dist: focal
    name: 'Ubuntu 20.04LTS'

sudo: required

language:
  - cpp

compiler:
  - gcc

addons:​
  apt:​
    packages:​
      - cmake​

script:
  - mkdir -p build && cd build && cmake .. && make && make test

